# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'age_estimation.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 781, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.image_label.setMinimumSize(QtCore.QSize(300, 0))
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.horizontalLayout.addWidget(self.image_label)
        self.response_text_edit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.response_text_edit.setObjectName("response_text_edit")
        self.horizontalLayout.addWidget(self.response_text_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.upload_image = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.upload_image.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.upload_image.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.upload_image.setObjectName("upload_image")
        self.verticalLayout.addWidget(self.upload_image)
        self.send_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.send_button.setObjectName("send_button")
        self.verticalLayout.addWidget(self.send_button)
        self.json_response = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.json_response.setMinimumSize(QtCore.QSize(0, 130))
        self.json_response.setText("")
        self.json_response.setObjectName("json_response")
        self.verticalLayout.addWidget(self.json_response)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "                               --- Select a model ---"))
        self.comboBox.setItemText(1, _translate("MainWindow", "OpenCV"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Yolo"))
        self.comboBox.setItemText(3, _translate("MainWindow", "MediaPipe"))
        self.comboBox.setItemText(4, _translate("MainWindow", "centerface"))
        self.comboBox.setItemText(5, _translate("MainWindow", "retinaface"))
        self.upload_image.setText(_translate("MainWindow", "Upload Image"))
        self.send_button.setText(_translate("MainWindow", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
